### ISSUE TITLE
Misspelled word 'Bulletin'

### ISSUE THREAD

**Issue by codename-abbott** [icchd/bulletin#7]
The word 'Bulletin' is misspelled.
https://en.oxforddictionaries.com/definition/bulletin

The name in the link should not be a problem, however. That is, if the change could be a potential technical hurdle.

**Comment by darksmo** [comment]
Ooops, good catch.... changed it anywhere!

**Comment by darksmo** [comment]
This means that is *All* changed, including the URL. Please use https://icchd.github.io/bulletin/ to access the tool!
